### ISSUE TITLE
Consider moving AdoptOpenJDK to chocolatey-coreteampackages

### ISSUE THREAD

**Issue by ExE-Boss** [johanjanssen/ChocolateyPackages#39]
See https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md for details.

---

/cc @majkinetor @gep13 @AdmiringWorm

**Comment by johanjanssen** [comment]
Can you give me some arguments about why I should consider it? What benefits does it offer?

**Comment by FranklinYu** [comment]
@johanjanssen The “benefit” is that you don't need to maintain it any more. I think it ultimately depends on you whether it’s a benefit.

**Comment by gep13** [comment]
@FranklinYu that is NOT what that Core Team Packages Repository is for. It is not intended as a dumping ground for packages that people don’t want to maintain anymore.  If packages are moved to that repository, the hope and expectation is that the same maintainer continues to maintain those packages.

**Comment by FranklinYu** [comment]
@gep13 Then what’s the benefit?

**Comment by majkinetor** [comment]
@johanjanssen 

The benefits are:

- **Automation**: We have automation set up, reporting, github releases etc.
- **Visibility**: if people are looking at some repository, its coreteam repository. The probability is highest that it will get fixed there
- **Package on-boarding**: it makes possible for any other tool depending on this package to get into the coreteam repository since we can't rely on 3rd party packages.

For this to happen package needs to get embedded and follow the other strict guidelines. For this package streams would also be a great option to have although we currently don't mandate it. I will be more then willing to help reviewing such eventual PR given the importance of having the stable JDK distribution.

**Comment by johanjanssen** [comment]
@majkinetor @FranklinYu @gep13 @ExE-Boss 

Personally, I'm not against moving to the coreteampackages, on the other hand, it works as is now. 

If the Chocolatey team would like to include AdoptOpenJDK (and maybe OpenJDK and others as well) then please let me know. In that case, we can work on moving the packages.

However please keep in mind that the Java downloads are quickly getting larger. Currently, the zip for AdoptOpenJDK is 200 MB. I read that embedded software should not exceed 200 MB. Is that a hard limit and still valid? Because then we run the risk of going over the limit when embedding packages.

Next, to that, there is quite some work to comply with all the guidelines. So in case we move forward with this, I would love to get some help :).

**Comment by majkinetor** [comment]
> Currently, the zip for AdoptOpenJDK is 200 MB. I read that embedded software should not exceed 200 MB. Is that a hard limit and still valid? Because then we run the risk of going over the limit when embedding packages.

Yes.

As far as I can see it is less then 200MB, depending on version and MSI. However its very close to it.
Probably embedding shouldn't be done then.

This could be migrated as 2 packages, `AdoptOpenJDK` and `AdoptOpenJRE` with streams for each. This currently doesn't support easy installation of older versions but AFAIK some planned upstream choco changes might allow for updating to minor/not-latest release (@gep13 would probably know more about it).

**Comment by FranklinYu** [comment]
> However please keep in mind that the Java downloads are quickly getting larger. Currently, the zip for AdoptOpenJDK is 200 MB. I read that embedded software should not exceed 200 MB. Is that a hard limit and still valid? Because then we run the risk of going over the limit when embedding packages.

I don’t think we are embedding the package even if we move it to coreteampackages.

**Comment by johanjanssen** [comment]
@FranklinYu, please see @majkinetor comments 
1 - "For this to happen package needs to get embedded and follow the other strict guidelines." 
2 - "As far as I can see it is less then 200MB, depending on version and MSI. However its very close to it. Probably embedding shouldn't be done then."

For now, I'll work with the new automated scripts in the new repo: https://github.com/johanjanssen/AdoptOpenJDKChocolateyPackages. That already makes it quite easy for me to create packages for new releases.
